rus_characters = {
    'Venti':'Венти',
    'Bennett':'Беннет',
    'Xiao':'Сяо',
    'Xingqiu':'Син Цю',
    'Zhongli':'Чжун Ли',
    'Ganyu':'Гань Юй',
    'Hu Tao':'Ху Тао',
    'Kaedehara Kazuha':'Кадзуха',
    'Jean':'Джин',
    'Diluc':'Дилюк',
    'Klee':'Кли',
    'Fischl':'Фишль',
    'Sucrose':'Сахароза',
    'Mona':'Мона',
    'Ningguang':'Нин Гуан',
    'Keqing':'Кэ Цин',
    'Kamisato Ayaka':'Аяка',
    'Tartaglia':'Тарталья',
    'Diona':'Диона',
    'Albedo':'Альбедо',
    'Yoimiya':'Ёимия',
    'Eula':'Эола',
    'Yanfei':'Янь Фэй',
    'Kaeya':'Кэйя',
    'Barbara':'Барбара',
    'Razor':'Рейзор',
    'Noelle':'Ноэлль',
    'Beidou':'Бей Доу',
    'Xiangling':'Сян Лин',
    'Chongyun':'Чун Юнь',
    'Qiqi':'Ци Ци',
    'Rosaria':'Розария',
    'Amber':'Эмбер',
    'Lisa':'Лиза',
    'Xinyan':'Синь Янь',
    'Traveler':'Путешенственник'
}

rus_element = {
    'Anemo': '<:Element_Anemo:870989749534486538> Анемо',
    'Pyro': '<:Element_Pyro:870989754454396998> Пиро',
    'Hydro': '<:Element_Hydro:870989753649102909> Гидро',
    'Electro': '<:Element_Electro:870989752801837056> Электро',
    'Geo': '<:Element_Geo:870989753271603230> Гео',
    'Dendro': '<:Element_Dendro:870989751908446250> Дендро',
    'Cryo': '<:Element_Cryo:870989751312846868> Крио',
}

rus_region = {
    'Inazuma': 'Инадзума',
    'Liyue':'Ли Юэ',
    'Mondstadt':'Мондштадт',
    'Dragonspine':'Драконий Хребет'
}

rus_weapon_type = {
    'Sword': 'Одноручный меч',
    'Bow': 'Лук',
    'Claymore': 'Двуручный меч',
    'Catalyst': 'Катализатор',
    'Polearm': 'Копьё'

}

rus_artifact_type = {
    'flower':'<:Icon_Flower_of_Life:871372154179059742> Цветок',
    'feather':'<:Icon_Plume_of_Death:871372154510397470> Перо',
    'hourglass':'<:Icon_Sands_of_Eon:871372154845933568> Часы',
    'goblet':'<:Icon_Goblet_of_Eonothem:871372154346827776> Кубок',
    'crown':'<:Icon_Circlet_of_Logos:871372154212605962> Корона',
}

rus_artifact_name = {
    "Initiate's Flower": 'Цветок посвященного', 
    "Initiate's Feather": 'Перо посвященного', 
    "Adventurer's Flower": 'Цветок искателя приключений', 
    "Adventurer's Tail Feather": 'Перо искателя приключений', 
    "Adventurer's Pocket Watch": 'Часы искателя приключений', 
    "Adventurer's Golden Goblet": 'Кубок искателя приключений', 
    "Adventurer's Bandana": 'Повязка искателя приключений', 
    "Lucky Dog's Clover": 'Клевер везунчика', 
    "Lucky Dog's Eagle Feather": 'Орлиное перо везунчика', 
    "Lucky Dog's Hourglass": 'Песочные часы везунчика', 
    "Lucky Dog's Goblet": 'Кубок везунчика', 
    "Lucky Dog's Silver Circlet": 'Серебрянная корона везунчика', 
    "Traveling Doctor's Silver Lotus": 'Серебряный лотос целителя', 
    "Traveling Doctor's Owl Feather": 'Совиное перо целителя', 
    "Traveling Doctor's Pocket Watch": 'Карманные часы целителя', 
    "Traveling Doctor's Medicine Pot": 'Чайник целителя', 
    "Traveling Doctor's Handkerchief": 'Платок целителя', 
    'Heart of Comradeship': 'Сердце товарищества', 
    'Feather of Homecoming': 'Перо возвращения домой', 
    'Sundial of the Sojourner': 'Солнечные часы временщика', 
    'Goblet of the Sojourner': 'Кубок временщика', 
    'Crown of Parting': 'Венок расставания', 
    "Tiny Miracle's Flower": 'Цветок маленького чуда', 
    "Tiny Miracle's Feather": 'Перо маленького чуда', 
    "Tiny Miracle's Hourglass": 'Песочные часы маленького чуда', 
    "Tiny Miracle's Goblet": 'Чашка маленького чуда', 
    "Tiny Miracle's Earrings": 'Серёжки маленького чуда', 
    "Berserker's Rose": 'Роза берсерка', 
    "Berserker's Indigo Feather": 'Перо берсерка', 
    "Berserker's Timepiece": 'Часы берсерка', 
    "Berserker's Bone Goblet": 'Костяной кубок берсерка', 
    "Berserker's Battle Mask": 'Боевая маска берсерка', 
    "Instructor's Brooch": 'Брошь инструктора', 
    "Instructor's Feather Accessory": 'Перо инструктора', 
    "Instructor's Pocket Watch": 'Карманные часы инструктора', 
    "Instructor's Tea Cup": 'Чайная кружка инструктора', 
    "Instructor's Cap": 'Кепка инструктора', 
    "Exile's Flower": 'Цветок изгнанника', 
    "Exile's Feather": 'Перо изгнанника', 
    "Exile's Pocket Watch": 'Карманныые часы изгнанника', 
    "Exile's Goblet": 'Кубок изгнанника', 
    "Exile's Circlet": 'Корона изгнанника', 
    "Guardian's Flower": 'Цветок защитника', 
    "Guardian's Sigil": 'Перо защитника', 
    "Guardian's Clock": 'Часы защитника', 
    "Guardian's Vessel": 'фляжка защитника', 
    "Guardian's Band": 'Повязка защитника', 
    'Medal of the Brave': 'Брошь храбреца', 
    'Prospect of the Brave': 'Надежды храбреца', 
    'Fortitude of the Brave': 'Стойкость храбреца', 
    'Outset of the Brave': 'Проводы храбреца', 
    'Crown of the Brave': 'Венок храбреца', 
    "Martial Artist's Red Flower": 'Алый цветок воина', 
    "Martial Artist's Feather Accessory": 'Перо воина', 
    "Martial Artist's Water Hourglass": 'Водяные часы воина', 
    "Martial Artist's Wine Cup": 'Винный бокал воина', 
    "Martial Artist's Bandana": 'Повязка воина', 
    "Gambler's Brooch": 'Брошь азартного игрока', 
    "Gambler's Feather Accessory": 'Перо азартного игрока', 
    "Gambler's Pocket Watch": 'Карманные часы азартного игрока', 
    "Gambler's Dice Cup": 'Стакан для когтей азартного игрока', 
    "Gambler's Earrings": 'Серёжки азартного игрока', 
    "Scholar's Bookmark": 'Закладка учёного', 
    "Scholar's Quill Pen": 'Перо учёного', 
    "Scholar's Clock": 'Часы учёного', 
    "Scholar's Ink Cup": 'Чернильница учёного', 
    "Scholar's Lens": 'Очки учёного', 
    'Tiara of Flame': 'Шаман огня', 
    'Tiara of Torrents': 'Шаман воды', 
    'Tiara of Thunder': 'Шаман молний', 
    'Tiara of Frost': 'Шаман льда', 
    "Gladiator's Nostalgia": 'Ностальгия гладиатора', 
    "Gladiator's Destiny": 'Судьба гладиатора', 
    "Gladiator's Longing": 'Стремление гладиатора', 
    "Gladiator's Intoxication": 'Пьянство гладиатора', 
    "Gladiator's Triumphus": 'Триумф гладиатора', 
    "Troupe's Dawnlight": 'Рассвет ансамбля', 
    "Bard's Arrow Feather": 'Оперение стрелы барда', 
    "Concert's Final Hour": 'Окончание концерта', 
    "Wanderer's String Kettle": 'Фляжка странника', 
    "Conductor's Top Hat": 'Цилиндр дирижёра', 
    "Thundersoother's Heart": 'Сердце усмиряющего гром', 
    "Thundersoother's Plume": 'Перо усмиряющего гром', 
    'Hour of Soothing Thunder': 'Время усмиряющего гром', 
    "Thundersoother's Goblet": 'Бокал усмиряющего гром', 
    "Thundersoother's Diadem": 'Корона усмиряющего гром', 
    "Thunderbird's Mercy": 'Милосердие буревестника', 
    'Survivor of Catastrophe': 'Переживший катастрофу', 
    'Hourglass of Thunder': 'Песочные часы грома', 
    'Omen of Thunderstorm': 'Предвестник бури', 
    "Thunder Summoner's Crown": 'Корона призывателя грома', 
    "Maiden's Distant Love": 'Далёкая душа юной девы', 
    "Maiden's Heart-stricken Infatuation": 'Тоска юной девы', 
    "Maiden's Passing Youth": 'Уходящая молодость юной девы', 
    "Maiden's Fleeting Leisure": 'Досуг юной девы', 
    "Maiden's Fading Beauty": 'Увядающая красота юной девы', 
    'In Remembrance of Viridescent Fields': 'Воспоминания об изумрудных лугах', 
    'Viridescent Arrow Feather': 'Оперение стрелы изумрудного охотника', 
    "Viridescent Venerer's Determination": 'Решимость изумрудного охотника', 
    "Viridescent Venerer's Vessel": 'Сосуд изумрудного охотника', 
    "Viridescent Venerer's Diadem": 'Венок изумрудного охотника', 
    "Witch's Flower of Blaze": 'Ведьмин огненный цветок', 
    "Witch's Ever-Burning Plume": 'Пылающее ведьмино перо', 
    "Witch's End Time": 'Ведьмин последний час', 
    "Witch's Heart Flames": 'Пламя ведьминого сердца', 
    "Witch's Scorching Hat": 'Тлеющая ведьмина шляпа', 
    "Lavawalker's Resolution": 'Решительность ступающего по лаве', 
    "Lavawalker's Salvation": 'Спасение ступающего по лаве', 
    "Lavawalker's Torment": 'Муки ступающего по лаве', 
    "Lavawalker's Epiphany": 'Просветление ступающего по лаве', 
    "Lavawalker's Wisdom": 'Мудрость ступающего по лаве', 
    'Royal Flora': 'Королевский цветок', 
    'Royal Plume': 'Королевское перо', 
    'Royal Pocket Watch': 'Королевские карманные часы', 
    'Royal Silver Urn': 'Королевская серебряная фляжка', 
    'Royal Masque': 'Королевская маска', 
    'Bloodstained Flower of Iron': 'Железное сердце рыцаря крови', 
    'Bloodstained Black Plume': 'Перо рыцаря крови', 
    'Bloodstained Final Hour': 'Час долга рыцаря крови', 
    "Bloodstained Chevalier's Goblet": 'Кубок рыцаря крови', 
    'Bloodstained Iron Mask': 'Железная маска рыцаря крови', 
    'Flower of Creviced Cliff': 'Цветок скальных трещин', 
    'Feather of Jagged Peaks': 'Перо зубчатых пиков', 
    'Sundial of Enduring Jade': 'Часы из прочного нефрита', 
    'Goblet of Chiseled Crag': 'Кубок из резного камня', 
    'Mask of Solitude Basalt': 'Маска из одинокого базальта', 
    "Summer Night's Bloom": 'Цветок равноденствия', 
    "Summer Night's Finale": 'Конец равноденствия', 
    "Summer Night's Moment": 'Час равноденствия', 
    "Summer Night's Waterballoon": 'Шар равноденствия', 
    "Summer Night's Mask": 'Маска равноденствия', 
    'Snowswept Memory': 'Занесённая снегом память', 
    "Icebreaker's Resolve": 'Решимость крушителя льда', 
    "Frozen Homeland's Demise": 'Гибель замёрзшей родины', 
    'Frost-Weaved Dignity': 'Морозная гордость', 
    "Broken Rime's Echo": 'Эхо осколков инея', 
    'Gilded Corsage': 'Позолоченная брошь', 
    'Gust of Nostalgia': 'Порыв ностальгии', 
    'Copper Compass': 'Медный компас', 
    'Goblet of Thundering Deep': 'Кубок оглушающих глубин', 
    'Wine-Stained Tricorne': 'Треуголка в пятнах вина', 
    'Flower of Accolades': 'Цветок почестей', 
    'Ceremonial War-Plume': 'Боевое перо командира', 
    'Orichalceous Time-Dial': 'Золотые часы', 
    "Noble's Pledging Vessel": 'Золотой кубок клятвы', 
    "General's Ancient Helm": 'Древний шлем генерала', 
    'Stainless Bloom': 'Незапятнанный цветок', 
    "Wise Doctor's Pinion": 'Перо мудрого лекаря', 
    'Moment of Cessation': 'Замершее мгновение', 
    'Surpassing Cup': 'Превосходящая чаша', 
    'Mocking Mask': 'Смеющаяся маска', 
    'Magnificent Tsuba': 'Великолепная цуба', 
    'Sundered Feather': 'Обрезанное перо', 
    'Storm Cage': 'Клетка грозовых облаков', 
    'Scarlet Vessel': 'Алый сосуд', 
    'Ornate Kabuto': 'Украшенный кабуто', 
    'Entangling Bloom': 'Опутывающий цветок', 
    'Shaft of Remembrance': 'Стрела воспоминаний', 
    "Morning Dew's Moment": 'Мгновение росы', 
    'Hopeful Heart': 'Полное надежд сердце', 
    'Capricious Visage': 'Непостоянный лик'}

def transform_abyss_name(old_name:str):
    floor, hall = old_name.split('-')
    new_name = f'Этаж {floor} Зал {hall}'
    return new_name