def get_content(content_type: str, lang: str):
    return LANGUAGES[lang][content_type]


LANGUAGES = {
    "Russian": {
        "TRANSLATED_COMMANDS": {
            "FUN_BORED": "Тебе скучно? Запусти эту команду и найди занятие для себя!",
            "FUN_QR": "Создаёт QR-код из текста",
            "FUN_RANDOM_ITEM": "Рандомные предметы! Используйте запятую, чтобы разделить ваши предметы",
            "FUN_RANDOM_NUM": "Генерирует псевдорандомное число",
            "FUN_ACTIVITY": "Позволяет использовать discord Activities",
            "FUN_CALCULATOR": "Открывает калькулятор",
            "PHASMO_ITEM": "Рандомный предмет из игры Phasmophobia",
            "PHASMO_MAP": "Рандомная карта из игры Phasmophobia",
            "GAME_RPS": "Начинает игру Камень ножницы бумага",
            "GAME_TTT_ONLINE": "Начинает игру Крестики-нолики",
            "GAME_TTT_BOT": "Начинает игру Крестики-нолики с ботом",
            "GAME_MONKEYMEMORY": "Начинает игру Monkey Memory",
            "GAME_TILES": "Начинает игру Пятнашки (Игра в 15)",
            "REACTIONROLE_ADD_ROLE": "Добавляет роль по реакции к сообщению",
            "REACTIONROLE_ADD_POST": "Добавляет сообщение для реакции",
            "REACTIONROLE_REMOVE_POST": "Удаляет сообщение для реакции",
            "REACTIONROLE_REMOVE_ROLE": "Удаляет роль по реакции у сообщения",
            "AUTOROLE_ADD_ROLE_TO_EVERYONE": "Добавляет роль к каждому участнику сервера",
            "AUTOROLE_DROPDOWN_CREATE": "Создаёт новое меню",
            "AUTOROLE_DROPDOWN_ADD_OPTION": "Добавляет опцию для меню",
            "AUTOROLE_DROPDOWN_LIST": "Показывает список всех меню",
            "AUTOROLE_DROPDOWN_LOAD": "Загружает меню с базы",
            "AUTOROLE_DROPDOWN_REMOVE_OPTION": "Удаляет опцию с меню",
            "AUTOROLE_DROPDOWN_SET_STATUS": "Устанавливает статус на меню",
            "AUTOROLE_DROPDOWN_DELETE": "Удаляет меню из базы. Не удаляет само сообщение!",
            "AUTOROLE_ON_JOIN_ADD": "Добавляет роль, которая выдаётся при заходе на сервер",
            "AUTOROLE_ON_JOIN_REMOVE": "Удаляет роль, которая выдаётся при заходе на сервер",
            "AUTOROLE_REMOVE_ROLE_FROM_EVERYONE": "Удаляет роль у всех участников сервера",
            "AUTOROLE_BUTTON_CREATE": "Создаёт сообщение для последующего прикрепления кнопок с ролями",
            "AUTOROLE_BUTTON_ADD_ROLE": "Добавляет новую кнопку с ролью к сообщению",
            "AUTOROLE_BUTTON_REMOVE_ROLE": "Удаляет кнопку с ролью в сообщении",
            "GENSHIN_BIND": "Привязывает Hoyolab UID к вашему аккаунту",
            "GENSHIN_CHARACTERS_LIST": "Показывает список персонажей",
            "GENSHIN_CHARACTERS": "Показывает подробный список персонажей",
            "GENSHIN_INFO": "Показывает информацию об аккаунте",
            "GENSHIN_STATISTICS": "Показывет статистику аккаунта",
            "LEVELS_ROLE_ADD": "Добавляет роль для уровня",
            "LEVELS_ROLE_ADD_START_ROLE": "Добавляет каждому начальную роль сервера",
            "LEVELS_CLEAR_MEMBERS_STATS": "Удаляет статистику участников сервера",
            "LEVELS_XP": "Добавляет опыт к участнику",
            "LEVELS_LEADERBOARD": "Показывает топ участников",
            "LEVELS_ROLE_REMOVE": "Удаляет уровень для роли",
            "LEVELS_ROLE_REPLACE": "Заменяет уровень для роли на другой",
            "LEVELS_ROLE_RESET": "Удаляет роли по уровням",
            "LEVELS_RESET_STATS": "Удаляет статистику у участника",
            "LEVELS_ROLE_LIST": "Показывает список ролей по уровню",
            "LEVELS_ROLE_SET_START_ROLE": "Устанавливает начальную роль по уровню",
            "LEVELS_ROLE_DELETE_START_ROLE": "Удаляет начальную роль по уровню",
            "LEVELS_ON_JOIN_ROLE_ADD": "Добавляет роль по уровню, каждому, кто присоединится на сервер",
            "LEVELS_ON_JOIN_ROLE_REMOVE": "Удаляет роль по уровню",
            "SERVER_OFFLINE_BOTS": "Показывает список всех ботов в оффлайне",
            "SERVER_ROLE_PERMS": "Показывает права у роли на сервере",
            "SERVER_ROLES": "Выводит все роли на сервере",
            "SERVER_BOT_NICK": "Устанавливает боту ник на сервере",
            "MISC_PING": "Показывает задержку бота",
            "MISC_SEND_IMAGE": "Отправляет картину в виде embed из ссылки",
            "MISC_ATTACHMENT": "Отправляет файл от имени бота",
            "INFO_USER": "Показывает информацию об участнике сервера",
            "INFO_BOT": "Показывает информацию о боте",
            "INVITE": "Выводит ссылку для приглашения бота",
            "MOD_ADD_ROLE": "Добавляет роль к участнику",
            "MOD_BAN": "Банит участника на сервере",
            "MOD_CLEAR": "Удаляет сообщения в канале",
            "MOD_CREATE_MUTED_ROLE": "Создаёт роль для мута",
            "MOD_KICK": "Кикает участника с сервера",
            "MOD_MUTE": "Выдаёт роль-мут участнику",
            "MOD_NICK": "Меняет ник у участника",
            "MOD_REMOVE_ROLE": "Удаляет роль у участника",
            "MOD_UNMUTE": "Убирает роль-мут у участника",
            "MUSIC_NPLAY": "Включает музыку с плеером",
            "MUSIC_PAUSE": "Ставит воспроизведение музыки на паузу",
            "MUSIC_PLAY": "Начинает воспроизведение музыки",
            "MUSIC_REPEAT": "Ставит музыку на повтор",
            "MUSIC_RESUME": "Продолжает воспроизведение музыки",
            "MUSIC_STOP": "Останавливает воспроизведение музыки",
            "MUSIC_SKIP": "Пропускает текущий трек",
            "MUSIC_QUEUE": "Показывает текущую очередь",
            "MUSIC_FORCE_STOP": "Используйте эту команду, если возникли проблемы с музыкой. (Может выдавать ошибку)",
            "MUSIC_PLAYLIST_ADD_TRACK": "Добавляет текущую песню в ваш плейлист",
            "MUSIC_PLAYLIST_DELETE_TRACK": "Удаляет песню из вашего плейлиста",
            "MUSIC_PLAYLIST_DELETE": "Удаляет ваш плейлист",
            "MUSIC_PLAYLIST_INFO": "Показывает список песен в вашем плейлисте",
            "MUSIC_PLAYLIST_PLAY": "Начинает проигрывать ваш плейлист или добавляет его в очередь",
            "MUSIC_PLAYLIST_COPY": "Копирует плейлист участника",
            "LANGUAGE": "Меняет язык у бота на вашем сервере",
            "EMBED_COLOR": "Меняет цвет сообщений (embed)",
            "TAGS_SET_CONTROL": "Разрешает или запрещает всем(@everyone) использовать теги",
            "TAG_CREATE": "Добавляет новый тег",
            "TAG_RAW": "Отправляет тег без форматирования",
            "TAG_RENAME": "Переименовывает тег",
            "TAG_LIST": "Показывает список тегов на сервере",
            "TAG_REMOVE": "Удаляет тег",
            "TAG_VIEW": "Открывает существующий тег",
            "TAG_EDIT": "Редактирует тег",
            "TAG_SET_CONTROL": "Разрешает или запрещает роли @everyone управлять тегами",
            "COMMAND_DISABLE": "Отключает команду/группу команд на вашем сервере",
            "COMMAND_ENABLE": "Включает команду/группу команд на вашем сервере",
            "STARBOARD_CHANNEL": "Меняет канал для starboard сообщений",
            "STARBOARD_LIMIT": "Устанавливает количество звезд, для появления в канале",
            "STARBOARD_STATUS": "Включает/выключает starboard",
            "STARBOARD_BLACKLIST_ADD": "Добавляет участника/роль/канал в чёрный список",
            "STARBOARD_BLACKLIST_LIST": "Показывает чёрный список",
            "STARBOARD_BLACKLIST_REMOVE": "Удаляет участника/роль/канал из чёрного списка",
            "NOTE_NEW": "Создаёт новую заметку",
            "NOTE_DELETE": "Удаляет заметку",
            "NOTE_LIST": "Показывает список ваших заметок",
            "GLOBAL_MUSIC_PLAYLIST": "Делает ваш плейлист глобальным. Вы можете слушать ваш плейлист где угодно!",
            "PRIVATE_ROOMS_CREATE_MENU": "Создаёт каналы для приватных комнат",
            "PRIVATE_ROOMS_CONTROL_CLOSE": "Закрыть комнату",
            "PRIVATE_ROOMS_CONTROL_OPEN": "Открыть комнату",
            "PRIVATE_ROOMS_CONTROL_HIDE": "Спрятать комнату",
            "PRIVATE_ROOMS_CONTROL_UNHIDE": "Раскрыть комнату",
            "PRIVATE_ROOMS_CONTROL_CHANGE_NAME": "Изменить название комнаты",
            "PRIVATE_ROOMS_CONTROL_BAN": "Забанить участника для комнаты",
            "PRIVATE_ROOMS_CONTROL_UNBAN": "Разбанить участника для комнаты",
            "PRIVATE_ROOMS_CONTROL_KICK": "Кикнуть участника из комнаты",
            "PRIVATE_ROOMS_CONTROL_TRANSFER_OWNERSHIP": "Передать право пользования комнаты",
            "PRIVATE_ROOMS_CONTROL_SET_LIMIT": "Установить лимит комнаты",
        },
        "ERRORS_DESCRIPTIONS": {
            "COG_DISABLED": "Эта команда отключена на этом сервере!",
            "COMMAND_DISABLED": "Эта команда или группа команд была отключена на этом сервере!",
            "TAG_NOT_FOUND": "Тег не найден!",
            "FORBIDDEN_TAG": "Этот тег нельзя использовать!",
            "NOT_TAG_OWNER": "Вы не владелец тега!",
            "UID_NOT_BINDED": "У вас не привязан UID!",
            "GI_ACCOUNT_NOT_FOUND": "Аккаунт с таким UID не найден!",
            "GI_DATA_NOT_PUBLIC": "Профиль закрыт! Откройте профиль на [сайте]("
            "https://www.hoyolab.com/genshin/accountCenter/gameRecord)",
            "NOT_BOT_OWNER": "Это команда доступна только владельцу бота!",
            "BOT_MISS_PERMS": "**У бота недостаточно прав!**\nНеобходимые права: ",
            "MISS_PERMS": "**У вас недостаточно прав!**\nНеобходимые права:",
            "CHECK_FAILURE": "Вы не можете использовать эту команду!",
            "OTHER_ERRORS_TITLE": "❌ Упс... Произошла непредвиденная ошибка!",
            "OTHER_ERRORS_DESCRIPTION": "Этот баг был отправлен создателю\n *Ошибка:* ```\n{error}\n```",
            "BOT_DONT_HAVE_PERMS": "**У бота недостаточно прав чтобы сделать это!**\nТребуется:",
            "DONT_HAVE_PERMS": "**У вас недостаточно прав для использования этой команды!**\nТребуется:",
            "FORBIDDEN": "У бота недостаточно прав чтобы сделать это",
            "BAD_ARGUMENT": "Вы ввели неверно один из аргументов!",
            "BOT_NOT_CONNECTED": "Бот не присоединён к голосовому каналу!",
            "NOT_CONNECTED_TO_VOICE_TEXT": "Присоединитесь к голосовому каналу с ботом!",
            "NOT_PLAYING": "Музыка не играет!",
            "NO_DATA_FOUND": "Ничего не найдено!",
            "GUILD_ONLY": "Эта команда только для сервера!",
            "PRIVATE_VOICE_NOT_SETUP": "Приватные комнаты не установлены на сервере!",
            "DONT_HAVE_PRIVATE_ROOM": "У вас нет приватной комнаты!",
        },
        "FUNC_RANDOM_NUMBER_OUT_CONTENT": "Рандомное число: `{}`",
        "FUNC_MEMBER_INFO": {
            "MEMBER_STATUS": {
                "online": "<:s_online:850792217031082051> В сети",
                "dnd": "<:dnd:850792216943525936> Не беспокоить",
                "idle": "<:s_afk:850792216732368937> Отошёл",
                "offline": "<:s_offline:850792217262030969> Не в сети",
            },
            "ABOUT_TITLE": "Информация о {}",
            "GENERAL_INFO_TITLE": "Общая информация:",
            "FULL_NAME_TEXT": "Полное имя",
            "BADGES_TEXT": "Значки:",
            "DISCORD_REGISTRATION_TEXT": "Дата регистрации в Discord:",
            "JOINED_ON_SERVER_TEXT": "Дата присоединения на сервер:",
            "CURRENT_STATUS_TEXT": "Текущий статус:",
            "TOP_ROLE_TEXT": "Высшая роль:",
            "ROLES_TEXT": "Роли:",
            "LEVELING": {
                "CURRENT_LEVEL_TEXT": "<:level:863677232239869964> **Уровень:** `{level}`",
                "CURRENT_EXP_TEXT": "<:exp:863672576941490176> **Опыт:** `{exp}/{exp_to_next_level}` Всего: `{exp_amount}`",
                "LEVELING_INFO_TITLE_TEXT": "Уровневая информация",
                "TOTAL_VOICE_TIME": "<:voice_time:863674908969926656> **Время в голосом канале:** `{voice_time:.2f}` час.",
            },
        },
        "BOT_INFO_COMMAND": {
            "BOT_INFORMATION_TITLE": "Информация об Asteroid Bot",
            "GITHUB_UPDATES": "**Обновления GitHub**",
            "GENERAL_INFORMATION": "Общая информация",
            "CREATED_AT": "**Создан**",
            "SERVERS_COUNT": "**Серверов:**",
            "USERS_COUNT": "**Пользователей:**",
            "TECHNICAL_INFORMATION": "Техническая информация",
            "BOT_VERSION": "**Версия бота:**",
            "LINES_OF_CODE": "**Строк кода:**",
            "LIBRARIES": "**Библиотеки**",
        },
        "FUNC_PING": "Задержка бота `{}` мс",
        "INVITE_COMMAND": {
            "INVITE_BUTTON_NO_PERMS": "Без разрешений",
            "INVITE_BUTTON_ADMIN": "Администратор",
            "INVITE_BUTTON_RECOMMENDED": "Рекомендуемый",
            "CLICK_TO_INVITE_TEXT": "Нажмите на кнопку, чтобы пригласить бота\nСтарый способ {link}",
        },
        "FUNC_ACTIVITIES": {
            "NOT_CONNECTED_TO_CHANNEL_TEXT": "Вы не подключены к голосовому каналу!",
            "WRONG_CHANNEL_TEXT": "Вы выбрали неверный канал! Выберите голосовой!",
            "JOIN_TEXT": "**Присоединиться**",
            "REQUESTED_BY_TEXT": "Запрошено {}",
        },
        "GAMES_NAMES": {"RPS": "Камень Ножницы бумага", "TTT": "Крестики Нолики"},
        "FUNC_INVITE_TO_GAME": {
            "SELF_INVITE": "Вы не можете пригласить себя!",
            "BOT_INVITE": "Вы не можете пригласить бота!",
            "INVITE_MESSAGE_CONTENT": "{}! {} приглашает тебя в игру {}",
            "BUTTON_AGREE": "Согласиться",
            "BUTTON_DECLINE": "Отказаться",
            "AGREE_MESSAGE_CONTENT": "Вы приняли приглашение!",
            "DECLINE_MESSAGE_CONTENT": "{} отказался от игры!",
            "TIMEOUT_MESSAGE_CONTENT": "От {} нет ответа!",
        },
        "GAME_RPS": {
            "RESULTS_TITLE": "`          ИТОГИ ИГРЫ            `",
            "RESULTS_TEXT": ""
            "**Игроки:** {} и {} \n"
            "**Количество сыгранных игр:** {} \n"
            "**Счёт:** {}:{} \n"
            "**Победитель:** {}",
            "RESULTS_GAME_NAME": "**Название игры: Камень ножницы бумага**",
            "RESULTS_TIE": "Ничья",
            "MADE_MOVE_TEXT": "Вы сделали свой ход",
            "PLAYERS_TEXT": "**{}** VS **{}**",
            "CURRENT_SCORE_TEXT": "**Счёт:** {}:{}\n" "**Игра:** {}/{}",
        },
        "GAME_TTT": {
            "GAME_NAME": "Крестики Нолики",
            "RESULTS_TITLE": "`          ИТОГИ ИГРЫ            `",
            "RESULTS_GAME_NAME": "**Игра: Крестики Нолики**",
            "RESULTS_TEXT": "**Игроки: {player1} И {player2}**\n**Победитель:** {winner}",
            "RESULTS_TIE": "Ничья",
        },
        "FUNC_MODERATION_CHANGE_NICK_TEXT": "Был изменён ник {} на `{}`",
        "FUNC_MODERATION_MUTE_MEMBER": {
            "CANNOT_MUTE_BOT_TEXT": "Вы не можете замутить бота!",
            "WAS_MUTED_TEXT": "{} был отправлен в мут!",
            "TIME_TEXT": "**Время**: {amount} {time_format}\n",
            "REASON_TEXT": "**Причина**: {reason}",
            "MUTED_ROLE_CREATED_TEXT": "Роль для мута `role_name` была создана!",
        },
        "FUNC_MODERATION_BAN_MEMBER": {
            "CANNOT_BAN_BOT_TEXT": "Вы не можете забанить бота!",
            "WAS_BANNED_TEXT": "{member} был забанен!",
            "REASON_TEXT": "**Причина**: {reason}",
            "SERVER": "\n**Сервер:** {guild}",
        },
        "FUNC_MODERATION_KICK_MEMBER": {
            "CANNOT_KICK_BOT_TEXT": "Вы не можете кикнуть бота!",
            "WAS_KICKED_TEXT": "{member} был кикнут!",
            "REASON_TEXT": "**Причина**: {reason}",
            "SERVER": "\n**Сервер:** {guild}",
        },
        "FUNC_MODERATION_CLEAR_MESSAGES": "Успешно удалено `{}` сообщений!",
        "MOD_COMMANDS_CONTENT": {"NOT_VOICE_CHANNEL_TEXT": "Данный канал не является голосовым!"},
        "PUBLIC_TAGS_COMMAND": {
            "TAGS_PUBLIC": "Теги теперь доступны всем!",
            "TAGS_FOR_ADMINS": "Теги теперь могут создавать только те, у кого есть право `Управлять сервером`!",
        },
        "FUNC_TAG_LIST": {
            "TAGS_LIST_TEXT": "Список тегов в {server}",
            "NO_TAGS_TEXT": "Список пуст!",
        },
        "TAG_ADD_COMMAND": {
            "TAG_ALREADY_EXISTS_TEXT": "Этот тег уже существует!",
            "TAG_CREATED_TEXT": "Тег `{tag_name}` успешно создан!",
            "TAG_EDITED_TEXT": "Тег `{tag_name}` успешно изменён!",
            "MODAL_TITLE": "Настройка Тега",
            "MODAL_SET_TITLE": "Заголовок",
            "MODAL_TITLE_PLACEHOLDER": "То, что будет наверху тега",
            "MODAL_SET_DESCRIPTION": "Описание",
            "MODAL_DESCRIPTION_PLACEHOLDER": "Напишите что-то интересное",
        },
        "TAG_REMOVE_COMMAND": {"TAG_REMOVED_TEXT": "Тег `{tag_name}` успешно удалён!"},
        "TAG_RENAME_TAG": {"TAG_RENAMED_TEXT": "Тег `{tag_name}` переименован в `{new_tag_name}`!"},
        "MUSIC_COMMANDS": {
            "ADDED_IN_QUEUE_DESCRIPTION_TEXT": "Было добавлено в очередь `{tracks_amount}` трек(ов)!\n{tracks}",
            "ADDED_IN_QUEUE_TITLE_TEXT": "Обновление очереди",
            "DISCONNECTED_TEXT": "Успешно остановлено и отключено!",
            "PAUSED_TEXT": "Воспроизведение музыки поставлено на паузу!",
            "RESUMED_TEXT": "Пауза снята!",
            "TRACK_SKIPPED_TEXT": "Музыка была пропущена",
            "PLAYING_TEXT": "Сейчас играет",
            "NAME_TEXT": "Название:",
            "DURATION_TEXT": "Продолжительность:",
            "LIVE_TEXT": "Прямая трансляция",
            "REQUESTED_BY_TEXT": "Запрошено {}",
            "MUSIC_NOT_FOUND_TEXT": "Музыка с таким названием/ссылкой не найдено!",
            "QUEUE_IS_EMPTY_TEXT": "Очередь пуста!",
            "CURRENT_QUEUE_TITLE_TEXT": "Текущая очередь",
            "CURRENT_SONG_TEXT": "Текущий трек",
            "MUSIC_PLAYLIST": {
                "PLAYLIST_TITLE_TEXT": "Плейлист: {playlist}",
                "PLAYLIST_UPDATE_TITLE_TRACK": "Обновление плейлиста: {playlist}",
                "ADDED_TEXT": "Добавлен запрос: `{query}`",
                "MUSIC_DELETED": "Удалена песня `{name}` из плейлиста `{playlist}`",
                "PLAYLIST_COPIED": "Плейлист скопирован!",
                "PLAYLIST_DELETE_TEXT": "Плейлист `{playlist}` удалён!",
            },
        },
        "FUNC_RANDOM_ITEMS": {
            "ITEMS_LIST": [
                "Успокоительное",
                "Термометр",
                "Фотокамера",
                "Направленный микрофон",
                "Свеча",
                "Благовоние",
                "Зажигалка",
                "Распятие",
                "Соль",
                "Штатив",
                "Датчик ЭМП",
                "Радиоприёмник",
                "Блокнот",
                "Лазерный проектор",
                "Видеокамера",
                "Слабый фонарик",
                "УФ-фонарик",
                "Сильный фонарик",
                "Датчик движения",
                "Неоновая палочка",
                "Датчик звука",
                "Камера с креплением на голову",
            ],
            "SELECT_BUTTON": "Выборка",
            "EXCEPTION_BUTTON": "Исключение",
            "SELECT_ITEMS_TEXT": "Выберите предметы",
            "START_RANDOM_BUTTON": "Рандом!",
            "EXIT_BUTTON": "Выйти",
            "EMBED_TITLE": "Рандомные предметы!",
            "SECOND_MESSAGE_CONTENT": "Здесь будет появляться предмет",
            "SELECTED_ITEMS_TEXT": "**Выбранные предметы: **\n",
        },
        "GENSHIN_BIND_COMMAND": "Вы привязали UID",
        "GENSHIN_STATISTICS_COMMAND": {
            "EMBED_WORLD_EXPLORATION_TITLE": "Genshin Impact. Статистика мира",
            "EXPLORED_TEXT": "Исследовано",
            "Inazuma": "Инадзума",
            "Dragonspine": "Драконий хребет",
            "FROSTBEARING_TREE_LEVEL_TEXT": "\nУровень Дерева Вечной Мерзлоты: `{level}`",
            "SACRED_SAKURA_LEVEL_TEXT": "\nУровень Благосклонности сакуры: `{level}`",
            "REPUTATION_LEVEL_TEXT": "\nУровень репутации: `{level}`",
            "ANEMOCULUS": "Анемокулов",
            "GEOCULUS": "Геокулов",
            "ELECTROCULUS": "Электрокулов",
            "COLLECTED_OCULUS_TEXT": "Собрано окулов",
            "COMMON_CHEST": "Обычных",
            "EXQUISITE_CHEST": "Богатых",
            "PRECIOUS_CHEST": "Драгоценных",
            "LUXURIOUS_CHEST": "Роскошных",
            "CHESTS_OPENED": "Открыто сундуков",
            "UNLOCKED_TELEPORTS": "Открыто телепортов",
            "UNLOCKED_DOMAINS": "Открыто подземелий",
            "MISC_INFO": "Остальное",
        },
        "GENSHIN_CHARACTERS_LIST_COMMAND": {
            "EMBED_GENSHIN_CHARACTERS_LIST_TITLE": "Genshin Impact. Персонажи",
            "CHARACTER_LEVEL": "Уровень",
            "CHARACTER_CONSTELLATION": "Созвездие",
            "CHARACTER_VISION": "Глаз бога",
            "CHARACTER_WEAPON": "Оружие",
        },
        "GENSHIN_CHARACTERS_COMMAND": {
            "INFORMATION_TEXT": "**Информация**",
            "CHARACTER_LEVEL": "Уровень",
            "CHARACTER_CONSTELLATION": "Созвездие",
            "CHARACTER_VISION": "Глаз бога",
            "CHARACTER_FRIENDSHIP": "Уровень дружбы",
            "WEAPON_TEXT": "**Оружие**",
            "WEAPON_NAME": "Название",
            "WEAPON_RARITY": "Редкость",
            "WEAPON_TYPE": "Тип",
            "WEAPON_LEVEL": "Уровень",
            "WEAPON_ASCENSION_LEVEL": "Уровень восхождения",
            "WEAPON_REFINEMENT_LEVEL": "Уровень пробуждения",
            "ARTIFACTS_TEXT": "**Артефакты**",
            "ARTIFACT_NAME": "Название",
            "ARTIFACT_RARITY": "Редкость",
            "ARTIFACT_LEVEL": "Уровень",
            "GENSHIN_CHARACTER_VISION": {
                "Anemo": "<:Element_Anemo:870989749534486538> `Анемо`",
                "Pyro": "<:Element_Pyro:870989754454396998> `Пиро`",
                "Hydro": "<:Element_Hydro:870989753649102909> `Гидро`",
                "Electro": "<:Element_Electro:870989752801837056> `Электро`",
                "Geo": "<:Element_Geo:870989753271603230> `Гео`",
                "Dendro": "<:Element_Dendro:870989751908446250> `Дендро`",
                "Cryo": "<:Element_Cryo:870989751312846868> `Крио`",
            },
            "GENSHIN_ARTIFACT_TYPE": {
                "1": "<:Icon_Flower_of_Life:871372154179059742> Цветок",
                "2": "<:Icon_Plume_of_Death:871372154510397470> Перо",
                "3": "<:Icon_Sands_of_Eon:871372154845933568> Часы",
                "4": "<:Icon_Goblet_of_Eonothem:871372154346827776> Кубок",
                "5": "<:Icon_Circlet_of_Logos:871372154212605962> Корона",
            },
        },
        "GENSHIN_INFO_COMMAND": {
            "NICKNAME_TEXT": "Ник в игре",
            "ADVENTURE_RANK_TEXT": "Ранг Приключений",
            "ACHIEVEMENTS_TEXT": "Достижений",
            "CHARACTERS_TEXT": "Персонажей",
            "SPIRAL_ABYSS_TEXT": "Витая Бездна",
            "PLAYER_INFO_TEXT": "Информация об игроке",
        },
        "SET_EMBED_COLOR_COMMAND": {
            "WRONG_COLOR": "Неверный формат цвета!",
            "SUCCESSFULLY_CHANGED": "Цвет сообщений успешно изменён!",
        },
        "SET_LANGUAGE_COMMAND": {"LANGUAGE_CHANGED": "Язык сменён на русский"},
        "LEVELS": {
            "FUNC_UPDATE_MEMBER": {
                "NOTIFY_GUILD_CHANNEL": "{member} получил `{level}-й` уровень и повышение до {role}",
                "NOTIFY_DM": "Вы получили `{level}-й` уровень и повышение до {role}",
            },
            "FUNC_TOP_MEMBERS": {
                "TITLES": "**ID | Участник | Текущий уровень**\n",
                "TOP_MEMBERS_TEXT": "Топ участников по уровню",
                "REQUESTED_BY_TEXT": "Запрошено",
                "LEVEL": "Уровень",
                "XP": "опыт",
                "EMPTY_LEADERBOARD": "Топа нет",
            },
        },
        "HELP_COMMAND": {
            "INFORMATION_TEXT": "Информация",
            "INFORMATION_CONTENT_TEXT": "```Подсказка: [обязательный аргумент] (необязательный аргумент)```",
            "REQUIRED_BY_TEXT": "Запрошено {user}",
            "PLUGINS_TEXT": "Плагины",
            "SELECT_MODULE_TEXT": "Выберите плагин",
            "DESCRIPTION_TEXT": "Описание:",
            "PLUGINS": {
                "MAIN_PAGE": "Главная страница",
                "AUTOROLE": "АвтоРоли",
                "FUN": "Развлечение",
                "GENSHINSTATS": "Статистика Genshin Impact",
                "LEVELS": "Уровни",
                "MISC": "Разное",
                "MODERATION": "Модерация",
                "MUSIC": "Музыка",
                "TAGS": "Теги",
                "UTILITIES": "Утилиты",
                "PRIVATEROOMS": "Приватные комнаты",
            },
        },
        "STARBOARD_FUNCTIONS": {
            "CHANNEL_WAS_SETUP_TEXT": "Канал был установлен!",
            "LIMIT_WAS_SETUP_TEXT": "Лимит звёзд был установлен до `{limit}`!",
            "STARBOARD_NOT_SETUP_TEXT": "Канал или лимит звёзд не были установлены!",
            "STARBOARD_ENABLED_TEXT": "Starboard был `включен`!",
            "STARBOARD_DISABLED_TEXT": "Starboard был `выключен`!",
            "JUMP_TO_ORIGINAL_MESSAGE_TEXT": "Перейти к сообщению!",
            "BLACKLIST_NO_OPTIONS_TEXT": "Должно быть что-то из `member`, `role`, `channel`",
            "EMPTY_BLACKLIST_TEXT": "Чёрный список пуст!",
            "BLACKLIST_ADDED_TEXT": "Добавлено",
            "BLACKLIST_REMOVED_TEXT": "Удалено",
            "BLACKLIST_TEXT": "⭐Starboard. Чёрный список",
            "MEMBERS": "Участники",
            "CHANNELS": "Каналы",
            "ROLES": "Роли",
        },
        "AUTOROLE_DROPDOWN": {
            "ADDED_ROLES_TEXT": "Добавлено: ",
            "REMOVED_ROLES_TEXT": "\nУдалено: ",
            "NO_OPTIONS_TEXT": "Нет опций",
            "CREATED_DROPDOWN_TEXT": "Меню создано!",
            "MESSAGE_WITHOUT_DROPDOWN_TEXT": "Сообщение не имеет меню!",
            "OPTIONS_OVERKILL_TEXT": "Вы не можете добавить больше 25 опций в меню1",
            "SELECT_ROLE_TEXT": "Выберите роль",
            "ROLE_ADDED_TEXT": "Роль добавлена!",
            "OPTION_NOT_FOUND_TEXT": "Не удалось найти опцию с таким именем!",
            "OPTIONS_LESS_THAN_1_TEXT": "Опций в меню не может быть меньше 1",
            "ROLE_REMOVED_TEXT": "Роль удалена!",
            "DROPDOWN_ENABLED_TEXT": "Меню включено!",
            "DROPDOWN_DISABLED_TEXT": "Меню выключено!",
            "DROPDOWN_SAVED_TEXT": "Сохранено!",
            "NOT_SAVED_DROPDOWNS": "Нет сохранённых меню!",
            "DROPDOWN_LOADED_TEXT": "Меню загружено!",
            "DROPDOWN_LIST": "Список меню с ролями",
            "DROPDOWN_NOT_FOUND": "Меню с этим именем не найдено!",
            "DROPDOWN_DELETED_TEXT": "Меню удалено! Не забудьте удалить сообщение!",
        },
        "AUTOROLE_ON_JOIN": {
            "ROLE_ADDED_TEXT": "Роль {role} Добавлена!",
            "ROLE_REMOVED_TEXT": "Роль {role} Удалена!",
        },
        "TIME_FORMATS": {
            "с": "сек.",
            "м": "мин.",
            "ч": "час.",
            "д": "дн.",
            "s": "сек.",
            "m": "мин.",
            "h": "час.",
            "d": "дн.",
        },
        "COMMAND_CONTROL": {
            "COMMAND_DISABLED": "Команда `{command_name}` была выключена!",
            "COMMAND_ENABLED": "Команда `{command_name}` была включена!",
        },
        "AUTOROLE_BUTTON": {
            "EVENT_REMOVED_ROLE_TEXT": "Удалено: {}",
            "EVENT_ADDED_ROLE_TEXT": "Добавлено: {}",
            "LIMIT_25_BUTTONS": "Достигнут лимит в 25 кнопок!",
            "COMMAND_ROLE_ADDED_TEXT": "Роль добавлена",
            "COMMAND_ROLE_REMOVED_TEXT": "Роль удалена",
            "AT_LEAST_LABEL_EMOJI_TEXT": "Должно быть хотя бы название кнопки(label) или эмодзи(emoji)",
            "NO_AUTOROLES": "Автороли не найдены!",
            "NOT_BUTTONS_AUTOROLE": "Название не соответствует автороли для кнопок!",
            "AUTOROLE_CREATED": "Создано!",
        },
        "NOTES_COMMANDS": {
            "NOTE_CREATED_TEXT": "**Заметка создана:** `{name}`",
            "NOTE_DELETED": "Заметка удалена!",
            "USER_NOTE_LIST": "Заметки {}",
            "JUMP_TO": "Перейти к сообщению",
        },
        "PRIVATE_VOICE": {
            "PRIVATE_ROOMS": "Приватные комнаты",
            "CREATE_ROOM": "Создать комнату",
            "ROOM_CONTROL": "Управление комнатой",
            "ROOM_CONTROL_TITLE": "Управление приватной комнатой",
            "ROOM_CONTROL_DESCRIPTION": "**Чтобы управлять приватной комнатой, вы можете: \n"
            "1. Нажимать на специальные кнопки.\n"
            "2. Использовать специальные команды `/private_rooms control`.\n"
            "3. Менять настройки канала напрямую.** \n"
            "Вы можете настроить комнату, когда она у вас есть.\n\n"
            "<:lock_close:959124362840113182> — `Закрыть комнату` \n"
            "<:lock_open:959124362890461254> — `Открыть комнату` \n"
            "<:eye_close:959124362890461325> — `Спрятать комнату` \n"
            "<:eye:959124362890473582> — `Раскрыть комнату` \n"
            "<:pencil:959124362798174319> — `Изменить название комнаты` \n"
            "<:minus:959124362835931236> — `Забанить участника для комнаты` \n"
            "<:plus:959124362882068550> — `Разбанить участника для комнаты` \n"
            "<:lightning:959124362974343169> — `Кикнуть участника из комнаты` \n"
            "<:crown:959124362823340052> — `Передать управление комнатой` \n"
            "<:pencil_2:959124362835927080> — `Установить лимит комнаты`",
            "SUCCESSFULLY_CREATED": "Приватные комнаты созданы!",
            "ROOM_CLOSED": "Комната закрыта",
            "ROOM_OPENED": "Комната открыта",
            "ROOM_HIDED": "Комната спрятана",
            "ROOM_UNHIDED": "Комната раскрыта",
            "PRIVATE_ROOM_CONTROL_MODAL": "Управление приватной комнатой",
            "ROOM_NAME": "Название комнаты",
            "MEMBER_ID": "ID участника",
            "REMOVE_LIMIT": "Удалить лимит",
            "SETUP_ROOM_LIMIT": "Установите лимит комнаты с помощью меню",
            "LIMIT_WAS_SETUP": "Лимит комнаты был установлен",
            "ROOM_NAME_WAS_SETUP": "Название комнаты было изменено",
            "NOT_ID": "Вы ввели не ID",
            "NOT_MEMBER_ID": "Участник с таким ID не найден",
            "MEMBER_WAS_BANNED": "Участник был забанен",
            "MEMBER_WAS_UNBANNED": "Участник был разбанен",
            "MEMBER_WAS_KICKED": "Участник был кикнут",
            "OWNERSHIP_TRANSFERED": "Владелец комнаты был смёнен",
            "DONT_HAVE_PRIVATE_ROOM": "У вас нет комнаты",
        },
    },
    "English": {
        "ERRORS_DESCRIPTIONS": {
            "COG_DISABLED": "This command disabled on this server!",
            "COMMAND_DISABLED": "This command or group of commands was disabled on this server!",
            "TAG_NOT_FOUND": "Tag not found!",
            "FORBIDDEN_TAG": "This tag cannot be used!",
            "NOT_TAG_OWNER": "You not owner of this tag!",
            "UID_NOT_BINDED": "You didn't tie UID!",
            "GI_ACCOUNT_NOT_FOUND": "Account with this UID not found!",
            "GI_DATA_NOT_PUBLIC": "Profile is private! Open profile on [site](https://www.hoyolab.com/genshin/accountCenter/gameRecord)",
            "NOT_BOT_OWNER": "Only owner can use this command!",
            "BOT_MISS_PERMS": "Bot don't have permission for this!**\nRequired permissions: ",
            "MISS_PERMS": "You don't have permission for this!**\nRequired permissions:",
            "CHECK_FAILURE": "You can't use this command!",
            "OTHER_ERRORS_TITLE": "❌ Oops... An unexpected error occurred!",
            "OTHER_ERRORS_DESCRIPTION": "This bug was sent to owner\n*Error:*\n``` {error} ```",
            "BOT_DONT_HAVE_PERMS": "**Bot don't have permission for this!**\nRequired permissions:",
            "DONT_HAVE_PERMS": "**You don't have permission for this!**\nRequired permissions:",
            "FORBIDDEN": "Bot doesn't have permission for this!",
            "BAD_ARGUMENT": "One of arguments is wrong!",
            "BOT_NOT_CONNECTED": "Bot doesn't connected to a voice channel!",
            "NOT_CONNECTED_TO_VOICE_TEXT": "Connect to voice channel with a bot",
            "NOT_PLAYING": "Music not playing!",
            "NO_DATA_FOUND": "Nothing found!",
            "GUILD_ONLY": "This command only for server!",
            "PRIVATE_VOICE_NOT_SETUP": "Private Rooms are not setup!",
            "DONT_HAVE_PRIVATE_ROOM": "You don't have a room!",
        },
        "FUNC_RANDOM_NUMBER_OUT_CONTENT": "Random number is `{}`",
        "FUNC_MEMBER_INFO": {
            "MEMBER_STATUS": {
                "online": "<:s_online:850792217031082051> Online",
                "dnd": "<:dnd:850792216943525936> Do not disturb",
                "idle": "<:s_afk:850792216732368937> Idle",
                "offline": "<:s_offline:850792217262030969> Offline",
            },
            "ABOUT_TITLE": "Information about {}",
            "GENERAL_INFO_TITLE": "General information:",
            "FULL_NAME_TEXT": "Full name",
            "BADGES_TEXT": "Badges:",
            "DISCORD_REGISTRATION_TEXT": "Date of registration in Discord:",
            "JOINED_ON_SERVER_TEXT": "Date of joined in server:",
            "CURRENT_STATUS_TEXT": "Current status:",
            "TOP_ROLE_TEXT": "Top role:",
            "ROLES_TEXT": "Roles:",
            "LEVELING": {
                "CURRENT_LEVEL_TEXT": "<:level:863677232239869964> **Level:** `{level}`",
                "CURRENT_EXP_TEXT": "<:exp:863672576941490176> **Exp:** `{exp}/{exp_to_next_level}` Total: `{exp_amount}`",
                "LEVELING_INFO_TITLE_TEXT": "Level Information",
                "TOTAL_VOICE_TIME": "<:voice_time:863674908969926656> **Time in voice channel:** `{voice_time:.2f}` hour.",
            },
        },
        "BOT_INFO_COMMAND": {
            "BOT_INFORMATION_TITLE": "Asteroid Bot Information",
            "GITHUB_UPDATES": "**GitHub Updates**",
            "GENERAL_INFORMATION": "General Information",
            "CREATED_AT": "**Created at**",
            "SERVERS_COUNT": "**Servers:**",
            "USERS_COUNT": "**Users:**",
            "TECHNICAL_INFORMATION": "Technical information",
            "BOT_VERSION": "**Bot version:**",
            "LINES_OF_CODE": "**Lines of code:**",
            "LIBRARIES": "**Libraries**",
        },
        "INVITE_COMMAND": {
            "INVITE_BUTTON_NO_PERMS": "Without permissions",
            "INVITE_BUTTON_ADMIN": "Administrator",
            "INVITE_BUTTON_RECOMMENDED": "Recommended",
            "CLICK_TO_INVITE_TEXT": "Click on button to invite bot!\nOld way {link}",
        },
        "FUNC_PING": "Bot latency is `{}` ms",
        "FUNC_ACTIVITIES": {
            "NOT_CONNECTED_TO_CHANNEL_TEXT": "You not connected to voice channel!",
            "WRONG_CHANNEL_TEXT": "You selected wrong channel! Select voice channel!",
            "JOIN_TEXT": "**JOIN**",
            "REQUESTED_BY_TEXT": "Requested by {}",
        },
        "GAMES_NAMES": {"RPS": "Rock Paper Scissors", "TTT": "Tic Tac Toe"},
        "FUNC_INVITE_TO_GAME": {
            "SELF_INVITE": "You can not invite yourself!",
            "BOT_INVITE": "You can not invite Bot!",
            "INVITE_MESSAGE_CONTENT": "{}! {} invited you in game {}",
            "BUTTON_AGREE": "Agree",
            "BUTTON_DECLINE": "Decline",
            "AGREE_MESSAGE_CONTENT": "You accept invite!",
            "DECLINE_MESSAGE_CONTENT": "{} refused to game!",
            "TIMEOUT_MESSAGE_CONTENT": "no response from {}!",
        },
        "GAME_RPS": {
            "RESULTS_TITLE": "`          Results            `",
            "RESULTS_TEXT": ""
            "**Players:** {} vs. {} \n"
            "**Rounds played:** {} \n"
            "**Score:** {}:{} \n"
            "**Winner:** {}",
            "RESULTS_GAME_NAME": "**Game name: Rock Paper Scissors**",
            "RESULTS_TIE": "Draw",
            "MADE_MOVE_TEXT": "You made move",
            "PLAYERS_TEXT": "**{}** vs. **{}**",
            "CURRENT_SCORE_TEXT": "**Score:** {}:{}\n**Match:** {}/{}",
        },
        "GAME_TTT": {
            "GAME_NAME": "Tic Tac Toe",
            "RESULTS_TITLE": "`          Results            `",
            "RESULTS_GAME_NAME": "**Name: Tic Tac Toe**",
            "RESULTS_TEXT": "**Players: {player1} and {player2}**\n**Winner:** {winner}",
            "RESULTS_TIE": "Draw",
        },
        "FUNC_MODERATION_CHANGE_NICK_TEXT": "Nick of {} was changed to `{}`",
        "FUNC_MODERATION_MUTE_MEMBER": {
            "CANNOT_MUTE_BOT_TEXT": "You can't mute bot!",
            "WAS_MUTED_TEXT": "{} was muted!",
            "TIME_TEXT": "**Timeout**: {amount} {time_format}\n",
            "REASON_TEXT": "**Reason**: {reason}",
            "MUTED_ROLE_CREATED_TEXT": "Muted role with name `{role_name}` created!",
        },
        "FUNC_MODERATION_BAN_MEMBER": {
            "CANNOT_BAN_BOT_TEXT": "You can't ban bot!",
            "WAS_BANNED_TEXT": "{member} was banned!",
            "REASON_TEXT": "**Reason**: {reason}",
            "SERVER": "\n**Server:** {guild}",
        },
        "FUNC_MODERATION_KICK_MEMBER": {
            "CANNOT_KICK_BOT_TEXT": "You can't kick bot!",
            "WAS_KICKED_TEXT": "{member} was kicked!",
            "REASON_TEXT": "**Reason**: {reason}",
            "SERVER": "\n**Server:** {guild}",
        },
        "FUNC_MODERATION_CLEAR_MESSAGES": "Successfully deleted `{}` messages!",
        "MOD_COMMANDS_CONTENT": {"NOT_VOICE_CHANNEL_TEXT": "This channel is not voice channel!"},
        "PUBLIC_TAGS_COMMAND": {
            "TAGS_PUBLIC": "Tags for now public!",
            "TAGS_FOR_ADMINS": "For now tags only for roles with `Manage Server` permission!",
        },
        "TAG_ADD_COMMAND": {
            "TAG_ALREADY_EXISTS_TEXT": "This tag already exists!",
            "TAG_CREATED_TEXT": "Tag `{tag_name}` successfully created!",
            "TAG_EDITED_TEXT": "Tag `{tag_name}` successfully edited!",
            "MODAL_TITLE": "Tag configuration",
            "MODAL_SET_TITLE": "Title",
            "MODAL_TITLE_PLACEHOLDER": "Write here title of tag",
            "MODAL_SET_DESCRIPTION": "Description",
            "MODAL_DESCRIPTION_PLACEHOLDER": "Write something interesting",
        },
        "TAG_REMOVE_COMMAND": {"TAG_REMOVED_TEXT": "Tag `{tag_name}` successfully removed!"},
        "TAG_RENAME_TAG": {"TAG_RENAMED_TEXT": "Tag `{tag_name}` renamed to `{new_tag_name}`!"},
        "FUNC_TAG_LIST": {
            "TAGS_LIST_TEXT": "Tags list on {server}",
            "NO_TAGS_TEXT": "No tags in this server!",
        },
        "MUSIC_COMMANDS": {
            "ADDED_IN_QUEUE_DESCRIPTION_TEXT": "Was/Were added to the queue `{tracks_amount}` track(s).\n{tracks}",
            "ADDED_IN_QUEUE_TITLE_TEXT": "Queue update",
            "DISCONNECTED_TEXT": "Successfully stopped and disconnected!",
            "PAUSED_TEXT": "Paused!",
            "RESUMED_TEXT": "Resumed!",
            "TRACK_SKIPPED_TEXT": "Track skipped",
            "PLAYING_TEXT": "Now playing",
            "NAME_TEXT": "Name:",
            "DURATION_TEXT": "Duration:",
            "LIVE_TEXT": "Live",
            "REQUESTED_BY_TEXT": "Requested by {}",
            "MUSIC_NOT_FOUND_TEXT": "Music with this name/url not found",
            "QUEUE_IS_EMPTY_TEXT": "Queue is empty!",
            "CURRENT_QUEUE_TITLE_TEXT": "Current queue",
            "CURRENT_SONG_TEXT": "Current track",
            "MUSIC_PLAYLIST": {
                "PLAYLIST_TITLE_TEXT": "Playlist: {playlist}",
                "PLAYLIST_UPDATE_TITLE_TRACK": "Playlist update: {playlist}",
                "ADDED_TEXT": "Added query: `{query}`",
                "MUSIC_DELETED": "Deleted track from `{playlist}` playlist `{name}`",
                "PLAYLIST_COPIED": "Playlist copied!",
                "PLAYLIST_DELETE_TEXT": "Playlist `{playlist}` deleted!",
            },
        },
        "FUNC_RANDOM_ITEMS": {
            "ITEMS_LIST": [
                "Sanity Pills",
                "Thermometer",
                "Photo Camera",
                "Parabolic Microphone",
                "Candle",
                "Smudge Sticks",
                "Lighter",
                "Crucifix",
                "Salt Shaker",
                "Tripod",
                "EMF Reader",
                "Spirit Box",
                "Ghost Writing Book",
                "D.O.T.S Projector",
                "Video Camera",
                "Flashlight",
                "UV Flashlight",
                "Strong Flashlight",
                "Motion Sensor",
                "Glow Stick",
                "Sound Sensor",
                "Head Mounted Camera",
            ],
            "SELECT_BUTTON": "Select",
            "EXCEPTION_BUTTON": "Except",
            "SELECT_ITEMS_TEXT": "Select items",
            "START_RANDOM_BUTTON": "Random!",
            "EXIT_BUTTON": "Exit",
            "EMBED_TITLE": "Random items!",
            "SECOND_MESSAGE_CONTENT": "Here will be appear item",
            "SELECTED_ITEMS_TEXT": "**Selected items: **\n",
        },
        "GENSHIN_BIND_COMMAND": "You binded UID",
        "GENSHIN_STATISTICS_COMMAND": {
            "EMBED_WORLD_EXPLORATION_TITLE": "Genshin Impact. World exploration",
            "EXPLORED_TEXT": "Explored",
            "Inazuma": "Inazuma",
            "Dragonspine": "Dragonspine",
            "FROSTBEARING_TREE_LEVEL_TEXT": "\nLevel of Frostbearing Tree: `{level}`",
            "SACRED_SAKURA_LEVEL_TEXT": "\nLevel of Sacred Sakura's Favor: `{level}`",
            "REPUTATION_LEVEL_TEXT": "\nReputation level: `{level}`",
            "ANEMOCULUS": "Anemoculus",
            "GEOCULUS": "Geoculus",
            "ELECTROCULUS": "Electroculus",
            "COLLECTED_OCULUS_TEXT": "Collected oculus",
            "COMMON_CHEST": "Common",
            "EXQUISITE_CHEST": "Exquisite",
            "PRECIOUS_CHEST": "Precious",
            "LUXURIOUS_CHEST": "Luxurious",
            "CHESTS_OPENED": "Chest's opened",
            "UNLOCKED_TELEPORTS": "Unlocked waypoints teleports",
            "UNLOCKED_DOMAINS": "Unlocked domains",
            "MISC_INFO": "Misc",
        },
        "GENSHIN_CHARACTERS_LIST_COMMAND": {
            "EMBED_GENSHIN_CHARACTERS_LIST_TITLE": "Genshin Impact. Characters",
            "CHARACTER_LEVEL": "Level",
            "CHARACTER_CONSTELLATION": "Constellation",
            "CHARACTER_VISION": "Vision",
            "CHARACTER_WEAPON": "Weapon",
        },
        "GENSHIN_CHARACTERS_COMMAND": {
            "INFORMATION_TEXT": "**Information**",
            "CHARACTER_LEVEL": "Level",
            "CHARACTER_CONSTELLATION": "Constellation",
            "CHARACTER_VISION": "Vision",
            "CHARACTER_FRIENDSHIP": "Friendship level",
            "WEAPON_TEXT": "**Weapon**",
            "WEAPON_NAME": "Name",
            "WEAPON_RARITY": "Rarity",
            "WEAPON_TYPE": "Type",
            "WEAPON_LEVEL": "Level",
            "WEAPON_ASCENSION_LEVEL": "Level of ascension",
            "WEAPON_REFINEMENT_LEVEL": "Level of refinement",
            "ARTIFACTS_TEXT": "**Artifacts**",
            "ARTIFACT_NAME": "Name",
            "ARTIFACT_RARITY": "Rarity",
            "ARTIFACT_LEVEL": "Level",
            "GENSHIN_CHARACTER_VISION": {
                "Anemo": "<:Element_Anemo:870989749534486538> `Anemo`",
                "Pyro": "<:Element_Pyro:870989754454396998> `Pyro`",
                "Hydro": "<:Element_Hydro:870989753649102909> `Hydro`",
                "Electro": "<:Element_Electro:870989752801837056> `Electro`",
                "Geo": "<:Element_Geo:870989753271603230> `Geo`",
                "Dendro": "<:Element_Dendro:870989751908446250> `Dendro`",
                "Cryo": "<:Element_Cryo:870989751312846868> `Cryo`",
            },
            "GENSHIN_ARTIFACT_TYPE": {
                "1": "<:Icon_Flower_of_Life:871372154179059742> Flower",
                "2": "<:Icon_Plume_of_Death:871372154510397470> Feather",
                "3": "<:Icon_Sands_of_Eon:871372154845933568> Hourglass",
                "4": "<:Icon_Goblet_of_Eonothem:871372154346827776> Goblet",
                "5": "<:Icon_Circlet_of_Logos:871372154212605962> Crown",
            },
        },
        "GENSHIN_INFO_COMMAND": {
            "NICKNAME_TEXT": "Nickname",
            "ADVENTURE_RANK_TEXT": "Rank of Adventure",
            "ACHIEVEMENTS_TEXT": "Achievements",
            "CHARACTERS_TEXT": "Characters",
            "SPIRAL_ABYSS_TEXT": "Spiral Abyss",
            "PLAYER_INFO_TEXT": "Information about player",
        },
        "SET_EMBED_COLOR_COMMAND": {
            "WRONG_COLOR": "Wrong color format",
            "SUCCESSFULLY_CHANGED": "Embed color was changed!",
        },
        "SET_LANGUAGE_COMMAND": {"LANGUAGE_CHANGED": "Language changed to English"},
        "LEVELS": {
            "FUNC_UPDATE_MEMBER": {
                "NOTIFY_GUILD_CHANNEL": "{member} reached level `{level}` and got role {role}",
                "NOTIFY_DM": "You reached level `{level}` and got role {role}",
            },
            "FUNC_TOP_MEMBERS": {
                "TITLES": "**ID | Member | Current Level**\n",
                "TOP_MEMBERS_TEXT": "Top members by level",
                "REQUESTED_BY_TEXT": "Requested by",
                "LEVEL": "Level",
                "XP": "xp",
                "EMPTY_LEADERBOARD": "Leaderboard is empty",
            },
        },
        "HELP_COMMAND": {
            "INFORMATION_TEXT": "Information",
            "INFORMATION_CONTENT_TEXT": "```Hint: [required argument] (optional argument)```",
            "REQUIRED_BY_TEXT": "Required by {user}",
            "PLUGINS_TEXT": "Plugins",
            "SELECT_MODULE_TEXT": "Select Module",
            "DESCRIPTION_TEXT": "Description:",
            "PLUGINS": {
                "MAIN_PAGE": "Main Page",
                "AUTOROLE": "Autoroles",
                "FUN": "Fun",
                "GENSHINSTATS": "Genshin Impact Statistics",
                "LEVELS": "Levels",
                "MISC": "Misc",
                "MODERATION": "Moderation",
                "MUSIC": "Music",
                "TAGS": "Tags",
                "UTILITIES": "Utilities",
                "PRIVATEROOMS": "Private Rooms"
            },
        },
        "STARBOARD_FUNCTIONS": {
            "CHANNEL_WAS_SETUP_TEXT": "Channel was set up!",
            "LIMIT_WAS_SETUP_TEXT": "Stars limit was set up to `{limit}`!",
            "STARBOARD_NOT_SETUP": "Channel or stars limit doesn't set up!",
            "STARBOARD_ENABLED_TEXT": "Starboard was `enabled`!",
            "STARBOARD_DISABLED_TEXT": "Starboard was `disabled`!",
            "JUMP_TO_ORIGINAL_MESSAGE_TEXT": "Jump to original message!",
            "BLACKLIST_NO_OPTIONS_TEXT": "Should be one of `member`, `role`, `channel`",
            "EMPTY_BLACKLIST_TEXT": "Blacklist is empty!",
            "BLACKLIST_ADDED_TEXT": "Added!",
            "BLACKLIST_REMOVED_TEXT": "Removed!",
            "BLACKLIST_TEXT": "⭐Starboard. Blacklist",
            "MEMBERS": "Members",
            "CHANNELS": "Channels",
            "ROLES": "Roles",
        },
        "AUTOROLE_DROPDOWN": {
            "ADDED_ROLES_TEXT": "Added Roles: ",
            "REMOVED_ROLES_TEXT": "\nRemoved Roles: ",
            "NO_OPTIONS_TEXT": "No options",
            "CREATED_DROPDOWN_TEXT": "Dropdown created!",
            "MESSAGE_WITHOUT_DROPDOWN_TEXT": "Message without dropdown!",
            "OPTIONS_OVERKILL_TEXT": "You can't add more than 25 options in dropdown!",
            "SELECT_ROLE_TEXT": "Select role",
            "ROLE_ADDED_TEXT": "Role added!",
            "OPTION_NOT_FOUND_TEXT": "Could not find an option with this name",
            "OPTIONS_LESS_THAN_1_TEXT": "Options in dropdown can't be less than 1",
            "ROLE_REMOVED_TEXT": "Role removed!",
            "DROPDOWN_ENABLED_TEXT": "Dropdown enabled!",
            "DROPDOWN_DISABLED_TEXT": "Dropdown disabled!",
            "DROPDOWN_SAVED_TEXT": "Dropdown saved!",
            "NOT_SAVED_DROPDOWNS": "No dropdowns saved!",
            "DROPDOWN_LOADED_TEXT": "Dropdown loaded!",
            "DROPDOWN_LIST": "Dropdowns list",
            "DROPDOWN_NOT_FOUND": "Dropdown with this name not found!",
            "DROPDOWN_DELETED_TEXT": "Dropdown successully deleted! Don't forget to delete a message",
        },
        "AUTOROLE_ON_JOIN": {
            "ROLE_ADDED_TEXT": "Role {role} Added!",
            "ROLE_REMOVED_TEXT": "Role {role} Removed!",
        },
        "TIME_FORMATS": {
            "с": "seconds",
            "м": "minutes",
            "ч": "hours",
            "д": "days",
            "s": "seconds",
            "m": "minutes",
            "h": "hours",
            "d": "days",
        },
        "COMMAND_CONTROL": {
            "COMMAND_DISABLED": "Command `{command_name}` was disabled!",
            "COMMAND_ENABLED": "Command `{command_name}` was enabled!",
        },
        "AUTOROLE_BUTTON": {
            "EVENT_REMOVED_ROLE_TEXT": "Removed: {}",
            "EVENT_ADDED_ROLE_TEXT": "Added: {}",
            "LIMIT_25_BUTTONS": "You have reached limit in 25 buttons",
            "COMMAND_ROLE_ADDED_TEXT": "Role added",
            "COMMAND_ROLE_REMOVED_TEXT": "Role removed",
            "AT_LEAST_LABEL_EMOJI_TEXT": "Should be at least label or emoji",
            "NO_AUTOROLES": "Autoroles doesn't exists!",
            "NOT_BUTTONS_AUTOROLE": "That's not autorole name for buttons!",
            "AUTOROLE_CREATED": "Created!",
        },
        "NOTES_COMMANDS": {
            "NOTE_CREATED_TEXT": "**Note created:** `{name}`",
            "NOTE_DELETED": "Note deleted!",
            "USER_NOTE_LIST": "Notes {}",
            "JUMP_TO": "Jump To Message",
        },
        "PRIVATE_VOICE": {
            "PRIVATE_ROOMS": "Private Rooms",
            "CREATE_ROOM": "Create Room",
            "ROOM_CONTROL": "Room Control",
            "ROOM_CONTROL_TITLE": "Private Room Control",
            "ROOM_CONTROL_DESCRIPTION": "**To control your room you can: \n"
            "1. Press the following buttons.\n"
            "2. Use special command `/private_rooms control`.\n"
            "3. Control from discord settings.** \n"
            "You can only use them when you have a private channel.\n\n"
            "<:lock_close:959124362840113182> — `Сlose your room` \n"
            "<:lock_open:959124362890461254> — `Open your room` \n"
            "<:eye_close:959124362890461325> — `Hide your room` \n"
            "<:eye:959124362890473582> — `Unhide your room` \n"
            "<:pencil:959124362798174319> — `Change room name` \n"
            "<:minus:959124362835931236> — `Ban a person in a room` \n"
            "<:plus:959124362882068550> — `Unban a person in a room` \n"
            "<:lightning:959124362974343169> — `Kick a person in a room` \n"
            "<:crown:959124362823340052> — `Transfer room owner` \n"
            "<:pencil_2:959124362835927080> — `Set room limit`",
            "SUCCESSFULLY_CREATED": "Private rooms created!",
            "ROOM_CLOSED": "Room closed",
            "ROOM_OPENED": "Room opened",
            "ROOM_HIDED": "Room hided",
            "ROOM_UNHIDED": "Room unhided",
            "PRIVATE_ROOM_CONTROL_MODAL": "Private Room Menu",
            "ROOM_NAME": "Room name",
            "MEMBER_ID": "Member ID",
            "REMOVE_LIMIT": "Remove limit",
            "SETUP_ROOM_LIMIT": "Setup room limit by clicking on select menu",
            "LIMIT_WAS_SETUP": "Limit was setup",
            "ROOM_NAME_WAS_SETUP": "Room name was changed",
            "NOT_ID": "You did not enter an ID",
            "NOT_MEMBER_ID": "Member with this ID not found!",
            "MEMBER_WAS_BANNED": "Member was banned",
            "MEMBER_WAS_UNBANNED": "Member was unbanned",
            "MEMBER_WAS_KICKED": "Member was kicked",
            "OWNERSHIP_TRANSFERED": "Room ownership was changed",
            "DONT_HAVE_PRIVATE_ROOM": "You don't have a room!",
        },
    },
}
